POST http://127.0.0.1:4050/newuser
Content-Type: application/json

{
    "name" : "Julian",
    "password" : "Password"
}

###

GET http://127.0.0.1:4050/getentry
Content-Type: application/json

{
    "id" : 2
}

###

POST http://127.0.0.1:4050/userreviews
Content-Type: application/json

{
    "user_id" : 1
}

###
POST http://127.0.0.1:4050/newentry 
Content-Type: application/json

{
    "rating" : "Top"
}