POST http://127.0.0.1:4050/newuser
Content-Type: application/json

{
    "name" : "Julian",
    "password" : "Password"
}

###

POST http://127.0.0.1:4050/getentry
Content-Type: application/json

{
    "id" : 1
}

###

POST http://127.0.0.1:4050/userreviews
Content-Type: application/json

{
    "user_id" : 1
}

###
POST http://127.0.0.1:4050/newentry 
Content-Type: application/json

{
    "rating" : "Top"
}

###

Post http://127.0.0.1:4050/newuser
Content-Type: application/json

{
    "name" : "guestTest11",
    "password" : "",
    "checkPassword" : ""
}

###
Post http://127.0.0.1:4050/validateuser
Content-Type: application/json

{
    "name" : "guest",
    "password" : "guest"
}

###
Post http://127.0.0.1:4050/verifytoken
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJzaWduSW5UaW1lIjoxNzEyMzEwMDgyMzM2LCJpYXQiOjE3MTIzMTAwODJ9.M3OkQ-ZqFL20cYTAmScJIQnntQ9MFJPjglKzVCmxtqA

###

Post https://bierbewertungsappbackend-production.up.railway.app/getentry
Content-Type: application/json

{
    "id" : 3
}

###

Get http://127.0.0.1:4050/calculated
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJzaWduSW5UaW1lIjoxNzEyMzEwMDgyMzM2LCJpYXQiOjE3MTIzMTAwODJ9.M3OkQ-ZqFL20cYTAmScJIQnntQ9MFJPjglKzVCmxtqA

###

get http://127.0.0.1:4050/getdata
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJzaWduSW5UaW1lIjoxNzEyMzEwMDgyMzM2LCJpYXQiOjE3MTIzMTAwODJ9.M3OkQ-ZqFL20cYTAmScJIQnntQ9MFJPjglKzVCmxtqA

###

Get  https://bierbewertungsappbackend-production.up.railway.app/calculated

###

//Auth flow
Post http://127.0.0.1:4050/validateuser
Content-Type: application/json

{
    "name" : "guest",
    "password" : "guest"
}

###
Get http://127.0.0.1:4050/calculated
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ3Vlc3QiLCJzaWduSW5UaW1lIjoxNzE0NjMwNzI1OTU4LCJpYXQiOjE3MTQ2MzA3MjcsImV4cCI6MTcxNDYzMDc4N30.vZ7sLZpQnbL3psbvNP6qDhDVWrYl6XPOUjaaCprkhmY


###
post http://127.0.0.1:4050/refreshtoken
Set-Cookie: refreshtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ3Vlc3QiLCJzaWduSW5UaW1lIjoxNzEzNDU5OTcwNTkzLCJpYXQiOjE3MTM0NTk5NzF9.VkUmjWaZuMFbYb3c7-9EjKPSBBQBU8wRgHSRnyjpbeY
Content-Type: application/json

{
    "userName" : "guest"
}


###
Get http://127.0.0.1:4050/calculated
Authorization: 
